apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego-app
  template:
    metadata:
      labels:
        app: eyego-app
    spec:
      containers:
      - name: eyego-app
        image: 501957928859.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest
        ports:
        - containerPort: 3000
